# Generated by Django 5.0.6 on 2024-09-13 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_question_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='pub_date',
        ),
    ]
